version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Builder
          command: |
            bash .circleci/compile.sh

      - run:
          name: Run unit tests
          command: |
            bash .circleci/unit_tests.sh

      - run:
          name: Run functional tests
          command: |
            sudo bash .circleci/functional_tests.sh

