version: 2.1
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Builder
          command: |
            bash .circleci/compile.sh

      - run:
          name: Run unit tests
          command: |
            bash .circleci/unit_tests.sh

