version: 2.1
jobs:
  build:
    resource_class: large
    machine:
      image: ubuntu-1604:201903-01
    environment:
      GOPATH: /home/circleci/go
      GO111MODULE: "on"
      CI_SPLUNK_VERSION: "7.3.2"
      CI_SPLUNK_FILENAME: splunk-7.3.2-c60db69f8e32-linux-2.6-amd64.deb
      CI_SPLUNK_HOST: 127.0.0.1
      CI_SPLUNK_PORT: 8089
      CI_SPLUNK_USERNAME: admin
      CI_SPLUNK_HEC_TOKEN: a6b5e77f-d5f6-415a-bd43-930cecb12959
      CI_SPLUNK_PASSWORD: helloworld
      CI_HEC_PROTOCOL: https
      CI_INDEX_EVENTS: circleci_events
      CI_INDEX_OBJECTS: circleci_objects
      CI_INDEX_METRICS: circleci_metrics
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Splunk
          command: |
            cd /tmp && wget -O $CI_SPLUNK_FILENAME 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version='$CI_SPLUNK_VERSION'&product=splunk&filename='$CI_SPLUNK_FILENAME'&wget=true'
            sudo dpkg -i $CI_SPLUNK_FILENAME
            # Set user seed
            hashed_pwd=$(sudo /opt/splunk/bin/splunk hash-passwd $CI_SPLUNK_PASSWORD)
            sudo tee /opt/splunk/etc/system/local/user-seed.conf > /dev/null << EOF
            [user_info]
            USERNAME = $CI_SPLUNK_USERNAME
            HASHED_PASSWORD = $hashed_pwd
            EOF
            # Add delete capability to admin role
            sudo tee -a /opt/splunk/etc/system/local/authorize.conf > /dev/null << EOF
            [role_admin]
            delete_by_keyword = enabled
            EOF
            # start Splunk
            sudo /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
            # Enable HEC services
            curl -X POST -u $CI_SPLUNK_USERNAME:$CI_SPLUNK_PASSWORD -k https://$CI_SPLUNK_HOST:$CI_SPLUNK_PORT/servicesNS/nobody/splunk_httpinput/data/inputs/http/http/enable
            # Create new HEC token
            curl -X POST -u $CI_SPLUNK_USERNAME:$CI_SPLUNK_PASSWORD -k -d "name=splunk_hec_token&token=$CI_SPLUNK_HEC_TOKEN" https://$CI_SPLUNK_HOST:$CI_SPLUNK_PORT/servicesNS/nobody/splunk_httpinput/data/inputs/http
            # Enable HEC new-token
            sudo /opt/splunk/bin/splunk http-event-collector enable -name splunk_hec_token -uri https://$CI_SPLUNK_HOST:$CI_SPLUNK_PORT -auth $CI_SPLUNK_USERNAME:$CI_SPLUNK_PASSWORD
            # Setup Indexes
            sudo /opt/splunk/bin/splunk add index $CI_INDEX_EVENTS -auth $CI_SPLUNK_USERNAME:$CI_SPLUNK_PASSWORD
            sudo /opt/splunk/bin/splunk http-event-collector update -uri https://$CI_SPLUNK_HOST:$CI_SPLUNK_PORT -name splunk_hec_token -auth $CI_SPLUNK_USERNAME:$CI_SPLUNK_PASSWORD -index $CI_INDEX_EVENTS
            # Restart Splunk
            sudo /opt/splunk/bin/splunk restart --accept-license --answer-yes --no-prompt
      - run:
          name: Builder
          command: |
            bash .circleci/compile.sh

      - run:
          name: Run unit tests
          command: |
            bash .circleci/unit_tests.sh

      - run:
          name: Run functional tests
          command: |
            export PYTHONWARNINGS="ignore:Unverified HTTPS request"
            bash .circleci/functional_tests.sh

