version: 2.1
jobs:
  build:
    machine:
       - image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
